# Generated by Django 4.2.26 on 2025-12-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0040_claimservice_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedclaim',
            name='predefined_reason',
            field=models.PositiveSmallIntegerField(db_column='PredefinedReason'),
        ),
    ]
