# Generated by Django 4.2.26 on 2025-12-04 11:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0041_alter_claim_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='rejection_note',
            field=models.TextField(blank=True, db_column='RejectionNote', help_text='Additional information about the rejection reason', null=True),
        ),
    ]
