# Generated by Django 4.2.26 on 2025-12-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0042_claim_rejection_note_alter_claim_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimitem',
            name='availability',
            field=models.BooleanField(db_column='availability', default=True),
        ),
        migrations.AlterField(
            model_name='claimservice',
            name='availability',
            field=models.BooleanField(db_column='availability', default=True),
        )
    ]
