# Generated by Django 4.2.26 on 2025-12-25 03:17

import claim.models
import core.fields
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0013_policy_membership_type'),
        ('product', '0026_productlaboratoryservice'),
        ('claim', '0043_alter_claim_admin_alter_claimitem_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimLaboratoryService',
            fields=[
                ('json_ext', models.JSONField(blank=True, db_column='JsonExt', null=True)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='ClaimLabServiceID', primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(db_column='ClaimLabServiceStatus')),
                ('qty_provided', models.DecimalField(db_column='QtyProvided', decimal_places=2, max_digits=18)),
                ('qty_approved', models.DecimalField(blank=True, db_column='QtyApproved', decimal_places=2, max_digits=18, null=True)),
                ('price_asked', models.DecimalField(db_column='PriceAsked', decimal_places=2, max_digits=18)),
                ('price_adjusted', models.DecimalField(blank=True, db_column='PriceAdjusted', decimal_places=2, max_digits=18, null=True)),
                ('price_approved', models.DecimalField(blank=True, db_column='PriceApproved', decimal_places=2, max_digits=18, null=True)),
                ('price_valuated', models.DecimalField(blank=True, db_column='PriceValuated', decimal_places=2, max_digits=18, null=True)),
                ('explanation', models.TextField(blank=True, db_column='Explanation', null=True)),
                ('justification', models.TextField(blank=True, db_column='Justification', null=True)),
                ('rejection_reason', models.SmallIntegerField(blank=True, db_column='RejectionReason', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('validity_from_review', core.fields.DateTimeField(blank=True, db_column='ValidityFromReview', null=True)),
                ('validity_to_review', core.fields.DateTimeField(blank=True, db_column='ValidityToReview', null=True)),
                ('audit_user_id_review', models.IntegerField(blank=True, db_column='AuditUserIDReview', null=True)),
                ('limitation_value', models.DecimalField(blank=True, db_column='LimitationValue', decimal_places=2, max_digits=18, null=True)),
                ('limitation', models.CharField(blank=True, db_column='Limitation', max_length=1, null=True)),
                ('remunerated_amount', models.DecimalField(blank=True, db_column='RemuneratedAmount', decimal_places=2, max_digits=18, null=True)),
                ('deductable_amount', models.DecimalField(blank=True, db_column='DeductableAmount', decimal_places=2, max_digits=18, null=True)),
                ('exceed_ceiling_amount', models.DecimalField(blank=True, db_column='ExceedCeilingAmount', decimal_places=2, max_digits=18, null=True)),
                ('price_origin', models.CharField(blank=True, db_column='PriceOrigin', max_length=1, null=True)),
                ('exceed_ceiling_amount_category', models.DecimalField(blank=True, db_column='ExceedCeilingAmountCategory', decimal_places=2, max_digits=18, null=True)),
                ('availability', models.BooleanField(db_column='availability', default=True)),
                ('lab_result', models.TextField(blank=True, db_column='LabResult', null=True)),
                ('specimen_type', models.CharField(blank=True, db_column='SpecimenType', max_length=50, null=True)),
                ('collection_date', core.fields.DateField(blank=True, db_column='CollectionDate', null=True)),
                ('result_date', core.fields.DateField(blank=True, db_column='ResultDate', null=True)),
            ],
            options={
                'db_table': 'tblClaimLabServices',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, claim.models.ClaimDetail, models.Model),
        ),
        migrations.AddField(
            model_name='claimlaboratoryservice',
            name='claim',
            field=models.ForeignKey(db_column='ClaimID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_services', to='claim.claim'),
        ),
        migrations.AddField(
            model_name='claimlaboratoryservice',
            name='lab_service',
            field=models.ForeignKey(db_column='LabServiceID', on_delete=django.db.models.deletion.DO_NOTHING, to='medical.laboratoryservice'),
        ),
        migrations.AddField(
            model_name='claimlaboratoryservice',
            name='policy',
            field=models.ForeignKey(blank=True, db_column='PolicyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='policy.policy'),
        ),
        migrations.AddField(
            model_name='claimlaboratoryservice',
            name='product',
            field=models.ForeignKey(blank=True, db_column='ProdID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claim_lab_services', to='product.product'),
        ),
    ]
