# Generated by Django 4.2.26 on 2026-02-06 07:43

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0044_claimlaboratoryservice_alter_claim_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='follow_up_issued_date',
            field=core.fields.DateField(blank=True, db_column='FollowUpIssuedDate', help_text='Date when follow-up was issued - only relevant when patient condition is Follow-Up', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='referral_date',
            field=core.fields.DateField(blank=True, db_column='ReferralDate', help_text='Date of referral - only relevant when patient condition is Referral', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='referral_reason',
            field=models.TextField(blank=True, db_column='ReferralReason', help_text='Reason for referral - only relevant when patient condition is Referral', null=True),
        ),
    ]
